theme: minima
title: Title
author: Matthew D. Hirt
email: mhirt@sebts.edu
description: > # this means to ignore newlines until "baseurl:"
  Once I figure out content, I will provide an amazing description here.

# social links
twitter_username: matthewhirt
github_username:  n/a

show_excerpts: true # set to false to remove excerpts on the homepage
